version: '2'

services:
  php:
    image: bitnami/php-fpm:latest
    # ports:
    #   - 9000:9000
    volumes:
      - ./app:/app
  apache:
    image: bitnami/apache:latest
    ports:
      - 80:8080
    volumes:
      - ./apache-vhost/myapp.conf:/vhosts/myapp.conf:ro
      - ./app:/app
    depends_on:
      - php
